# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49825909ce54a091a3a1a5633e870a39709eae0148f7ac35e7f2bbadc35698e636c3d58b23299380513181d62fa4a4ace517f970589e2d6fed282054ac29099

test:
  secret_key_base: e848aa0ad3595906345ccacfffab38cb71e722521f7c9bf318e1984f0a66b1160e9839b59fe230646340c6d30683904c96a7dbdefa54abdb68bbdea7c249df44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
